# client_secret de la client application "Mirage Availability PAPI" (Exchange), cifrado AES/CBC.
# La identidad del consumidor no cambia por ambiente: mismo valor en local y cloud.
papi.client.secret=![Oqhukje8B4KORiOsHj/rrEh0AgYIhxYoDOLHRDpMOv4ea9EAVCaaZzli0ggbP9Xa]
