# Configuración de la aplicación. Sin secretos (el client_secret va cifrado en secure-<env>.properties).
# Puerto local: 8084 (8081 erp, 8082 logistics, 8083 papi). En CloudHub se pisa con http.port=8081.
http.port=8084

# Consola APIkit: started en local; stopped en la nube
api.console.state=started

# API Manager: ID de la API instance (se completa al registrar la API)
api.id=21188336

# Process API que consume esta Experience API (ACB corre una app a la vez: se apunta a la PAPI en CloudHub)
papi.host=mirage-availability-papi-6bdyqf.5sc6y6-2.usa-e2.cloudhub.io
papi.port=443
papi.protocol=HTTPS

# Identidad de esta app como consumidor (client application "Mirage Storefront XAPI" en Exchange)
xapi.client.id=0e4b124b734e464abc6aaab520df88c2
